export const reducerCases = {
    TOGGLE_LOGIN_MODAL:"TOGGLE_LOGIN_MODAL",
    TOGGLE_SIGNUP_MODAL:"TOGGLE_SIGNUP_MODAL",
    CLOSE_AUTH_MODAL:"CLAUSE_AUTH_MODAL",
    SET_USER:"SET_USER",
    SWITCH_MODE:"SWITCH_MODE",
    SET_SERVICE_DATA:"SET_SERVICE_DATA",
    HAS_USER_ORDER:"HAS_USER_ORDER",
    ADD_REVIEW:"ADD_REVIEW"
}